[package]
name = "test_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.10.0"
actix-web = "3.3.3"
actix-files = "0.5.0"
log = "0.4.14"
env_logger = "0.9.0"
screen-share-codenames-server = { path = "../server" }
